[workspace]
resolver = "3"
members = [
    "fastly/async-macros",
    "fastly/async",
    "fastly/demo-server",
]
default-members = [
    "fastly/async-macros",
    "fastly/async",
]

[workspace.package]
edition = "2024"
license = "LicenseRef-OQL-1.3"

[workspace.dependencies]
async-task = "4"
fastly = "0.11.13"
fastly-shared = "0.11.13"
fastly-sys = "0.11.13"
futures = "0.3.32"
http = "1.4.0"
proc-macro2 = "1"
quote = "1"
syn = "2"
tracing = "0.1.44"

fastly-async = { path = "fastly/async" }
fastly-async-macros = { path = "fastly/async-macros" }
