[package]
name = "fastly-async"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
async-task.workspace = true
fastly.workspace = true

fastly-async-macros = { workspace = true, optional = true }
ordermap.workspace = true

[features]
macros = ["dep:fastly-async-macros"]
